# Generated by Django 2.0.6 on 2018-07-04 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
