# Generated by Django 2.0.6 on 2018-07-04 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_task_archive_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-deadline']},
        ),
    ]
